### ISSUE TITLE
Control few VESC's via CAN bus

### ISSUE THREAD

**Issue by SystemDiagnosticss** [SolidGeek/VescUart#29] opened 2021-08-06 13:45 UTC
Hi. Thank's for great lib.
I have some ask.
I want to connect first VESC to Arduino via UART and second VESC connect to CAN BUS of first VESC like in this [article](https://www.lp-electronic.com/vesc/connect-two-vesc-via-can-bus/#:~:text=Vedders%20VESC%20allows%20the%20connection,4wd%20or%20whatever%20you%20like.) 
So connection is work I check it with vesc tool. 
So how I can control second VESC if I send command via UART. Can I somewhere in the code apply vesсid?
Is it possible?

**Comment by vicgwee** [comment] 2021-08-10 05:37
Is this a duplicate of #7 ?

**Comment by SolidGeek** [comment] 2022-05-06 13:21
This is indeed a duplicate. This has been implemented using COMM_FORWARD_CAN

**Closed by SolidGeek** 2022-05-06 13:21 UTC
